### PR TITLE
Build libpng from source

### PR DESCRIPTION
**Pull request by VPInventions**
libpng 1.6.37 has been integrated to the build.

### CODE REVIEW

**Comment by perdrix52** [comment]
I'm not awfully happy to make a change to the release of a library this close to releasing 4.2.0

What impelled you to make this change at this point - this really is a change that should have been discussed before it was done.

As you should know from the readme readme file I left behind: I deliberately build libpng 1634 separately from DSS and only imported the .lib file into DSS as it was not the cleanest of code to integrate.

Where are you writing the output lib files?  lpng1637/x64/Debug , lpng1637/x64/Release lpng1637/x86/Debug lpng1637/x86/Release I hope?   As that is the standard we're used for the other libraries.

Sorry if I'm being a pain, but right now I'm inclined to refuse this merge

**Comment by perdrix52** [comment]
Oh yes I forgot to say - are you SURE it's OK to delete the define of WIN32 in the x64 build.  My memory say that it was needed for both 32 bit and 64 bit builds.

David

**Comment by VPInventions** [comment]
There is no need to make this change for 4.2.0 release. I've created a branch which can be merged to the master branch later, if everyone is ok with it. It is something for the future.

The lpng branch does not affect the release, right?

The only reason to make the change was the fact that DSS repository can not be compiled with latest VS 2017, because of the outdated libpng lib file.

I've made another commit which changes the output and intermediate directory to .\$(PlatformTarget)\$(Configuration) like other libs. But this is not correct if the files must be written to lpng1637. I'll fix that.

I've checked the libpng source code and it seems that it is ok to delete WIN32 from x64 defines. It does not actually matter for libpng, whether the define is there or not.

**Comment by perdrix52** [comment]
OK that's good - I'll be a lot happier to merge this after 4.2.0 ships. 

Same config as other projects works for me

As for not being able to build, using the lib file for if you can find VS2017 15.5.7 ...

**Comment by perdrix52** [comment]
I am clising this as was discussed

**Pull request closed without merging**
