### PR TITLE
Converted CCheckAbove to be CheckAbove in namespace DSS.

### PR DESCRIPTION
**Pull request by aiustin**

### CODE REVIEW

**Comment by perdrix52** [comment]
Hi there Iustin.  I thing it would be better if you also added a QStringValidator?

Is it possible to do one of those that accepts arbitrarily long numbers, OR a one or two digit number with a percent at the end?

**Comment by aiustin** [comment]
Sure. I'll take look. I also thought it needs some kind of validation but I was not sure if you're looking to just port the code as it is and improve later or improve while porting :).
It should be possible to have both formats but even if it's not we can always have 2 regexps :)
I'll disable the Ok button while validation fails - is that an acceptable user feedback?
Apologies for taking a bit longer to reply/work on this, but I'm moving house on Tuesday and there's a ton of stuff to deal with.

**Comment by perdrix52** [comment]
Normally you set the validator on the input control and it only allows the user to type what the regex permits.  See e.g. RenameGroup.cpp

**Comment by aiustin** [comment]
ok. 
Only positive integers or also negative ones? 
Also if it's only integers should I change the conversion to use int types instead of double? I mean is there a specific reason it was double?

**Comment by perdrix52** [comment]
Sorry floats are allowed. So regional "decimal" point validation needed?  Does RegExp support that?

**Comment by aiustin** [comment]
Ok. I read the answer. It's a fair point. A custom QValidator for these cases should be easy enough to write using QLocale::float for locale-aware validation. That's actually what they're doing internally in QIntValidator except they have access to the private interface.

**Comment by perdrix52** [comment]
source of QDoubleValidator is an interesting read too.

**Comment by aiustin** [comment]
Added an improved validator.

**Comment by perdrix52** [comment]
Nice! Code merged

 

David

**Pull request merged**
