### PR TITLE
Fix rect changes

### PR DESCRIPTION
**Pull request by mtoeltsch**
Correct replacement of CRect with DSSRect has been checked.
Correct replacement of CPoint with QPoint has been checked.
Correct replacement of CPointExt with QPointF has been checked.
Functions IsInRect and PtInRect have been replaced to 100% mimic old behaviour.
Loop borders have been checked to 100% mimic the old behaviour, even if old bugs have not been corrected.

### CODE REVIEW

**Comment by perdrix52** [comment]
I specifically want the new code to use DSSRect.contains() and you seem to have chosen to ignore that and use a variant of CPointExt.IsInRect() by any other name - please will you explain why you aren't using DSSRect.contains()

David

**Comment by mtoeltsch** [comment]
DSSRect::contains() leads to code like this:

DSSRect rc{ 0, 0,
    m_rcResult.width(), m_rcResult.height() };
if (rc.contains(ptOut))

This is ugly. The much better solution is to use a function for it. 
See the difference! You can do it in a single line of code:

if (DSS::pointIsInRect(ptOut, 0, 0, m_rcResult.width(), m_rcResult.height()))

**Comment by perdrix52** [comment]
Hmm My concern is we now have two ways to check if a point is in a rectangle, not one (IOW two places to get it wrong!!).  There's no semantic difference between point.isInRect and rect.contains(point) so the doesn't add any difficulty in comprehension or conversion.    There's lots of code using rect.contains(point) which you've not changed AFAICT.     Looking further at the code I see you replaced QPointF with QPoint in a number of places - I've no problem with that so long as you are sure that this won't cause a problem (if the old code used CRect there, that's fine).

D.

**Comment by mtoeltsch** [comment]
I have removed ALL places of DSSREct::contains(), simply because that member-function does not exist any more.

All checks are handled in those two functions, directly one below the other. They mimic the old code 100%. If we find (old) bugs, we simply fix them in those functions. I agree that we should remove one of the two functions after the Qt change is 100% finished to have the check at a single place. 
BTW: DSSRect::contains also had 2 versions.

There indeed is a semantic difference between pointIsInRect and DSSRect::contains. If you look at the code, we have no need for DSSRect::contains (there's no semantic needing that). What we actually need is QPoint(F)::IsPointInRect(const DSSRect&); Of course that is not possible, because we cannot extend the QPoint(F) classes as it comes with Qt. 
Therefore the next best solution is a function that takes a QPoint(F) as const-ref.
That's what I did. 

I replaced QPointF with QPoint at one or two places. And only, because the old code used CPoint and not CPointExt. 
So that was a fix.

**Comment by perdrix52** [comment]
Well in that case please reinstate it and use it

David

**Comment by perdrix52** [comment]
I didn't put it there just for you to delete

**Comment by mtoeltsch** [comment]
I'm confused. What do you want me to do exactly?

**Comment by perdrix52** [comment]
I want you to reinstate the two DSSRect.contains member functions and use them not the functions you defined.

**Comment by mtoeltsch** [comment]
I have
- spent 30 hours,
- found 24 bugs,
- seen thousands of changes and even more lines of code,
- made hundreds of code- and design improvements.

That pull-request is the result of my efforts.
There is not a single argument for using a MF contains(), but a few for the functions I use. I'm sorry, I will not re-design it.

**Comment by perdrix52** [comment]
You were not asked to do anything more than inspect the code and find problems.   I didn't ask you to throw away DSSRect.contains() (did you not even consider ASKING, or consider that I might not want you to do that).

I didn't ask you to make 100s of other code and design "improvements", and it fact if you'd asked I'd have said you should not do that and should concentrate soleley on the code inspection.

**Comment by perdrix52** [comment]
And (for what it is worth) why do you consider that  QPoint(F)::IsPointInRect(const DSSRect&); is in any way semantically different from DSSRect.contains(QPoint(F));

**Comment by perdrix52** [comment]
Look like I will be spending a lot of time reworking your changes for the Point/Rect issue, and then going through the other changes you made and applying most of them to the master branch as individual commits (not one huge commit).   Where you've simply replaced a for loop using indices/iterators with a "range for", probably not as that's just making a change because it is prettier.   Some of them I won't use - for example - your changes to BatchStacking aren't needed as Iustin is completely rewriting that in Qt.

I accept that you have probably forgotten more about C++ templates than I ever knew, and I greatly appreciate the huge amount of work you have put in to implementing the SIMD enhancements and adding test cases, and indeed in doing this code inspection.   Please consider how you'd react if you'd just implemented some new code and someone came along that said "No, don't like that, I'm going to throw it out".

Let's be quite clear: As the code owner, I get to be the final arbiter on the changes that are applied to DSS.

**Comment by mtoeltsch** [comment]
My only goal was and is to improve DeepSkyStacker. Not to upset someone.
We obviously have different views about C++ designs, but that's normal. 

I can offer to go through my changes once more and pick those that only affect the CRect/CPoint(Ext) changes. I would apply them to a new branch.

Let me know if you would like me to do that.

**Comment by perdrix52** [comment]
No need to do that, I'll pick this up from here, and close this PR once I picked out all the changes I want.

BTW I don't thing that making the DSSRect ctors constexpr will have gained anything as most of the rects created in the code use values that are only known at run time rather than compile time.

D.

**Comment by mtoeltsch** [comment]
Constexpr:
You are right. This just provides the option to define compile-time constants if needed.

**Comment by mtoeltsch** [comment]
But please note that (e.g. STL) defines classes and functions constexpr more and more.

**Comment by perdrix52** [comment]
Closed as discussed

**Pull request closed without merging**
