### PR TITLE
refactoring *.ui (moc) connections, to compile time c++ 11 ones

### PR DESCRIPTION
**Pull request by Rational-pi**
Refactoring runtime Qt connections generated by moc from *.ui files to compile-time ones in cpp code.
/!\ AskRegistering is actualy a CDialog even though AskRegistering.ui exists /!\

### CODE REVIEW

**Comment by perdrix52** [comment]
WHY

**Comment by Rational-pi** [comment]
Everything we can offload from predecessors macros/moc is a plus in maintainability, ease of code navigation, and safety. The number of bugs I fixed that were caused by connections in UI files doesn't fit on my 10 fingers.

**Review by perdrix52 — CHANGES_REQUESTED** [review]
Looking at the code please would you clarify why you wrote e.g. :

    connect(ui->buttonBox, &QDialogButtonBox::accepted, this, qOverload<>(&QDialog::accept));
    
AFAIK QDialog::accept doesn't have multiple overloads so why do you need the qOverload<>

In which case I believe the qOverload<> is redundant and confusing

Unless of course ...

**Comment by Rational-pi** [comment]
I agree, QDialog::accept does not have overloads, so it is redundant and confusing.
It's a remainder of my refactoring process; moc wrote it like this and I missed it.
I will change that.
I will also look at AskRegistering.

**Comment by Rational-pi** [comment]
Done :) , I removed confusing qOverloads and finished ported AskRegistering.
I confirmed that translations were working with the new dialog.
I did not clean MFC translation files of the old entries as I am not very knowledgeable about that technology.

**Comment by perdrix52** [comment]
Good!  I do NOT want the .rc files touched until the porting work is totally completed (at which time they can be deleted).

**Pull request merged**
