### PR TITLE
Replace CSmartPtr

### PR DESCRIPTION
**Pull request by mtoeltsch**
Replace the classes CSmartPtr and CRefCnt with STL shared_ptr and/or unique_ptr.

### CODE REVIEW

**Comment by perdrix52** [comment]
Is it ready to merge?  GitHub still shows it as "work in progress" ...

**Comment by mtoeltsch** [comment]
I doubt very much that it's ready to merge. There will certainly be conflicts with code that was added for Qt.

**Comment by mtoeltsch** [comment]
Careful review of the changes is required! 
Although there are no conflicts with the master, there might be regressions caused by the changes for Qt plus the changes for shared_ptr.

**Review by perdrix52 — APPROVED** [review]
I've looked through the changes and I don't think they'll break anything.  

If they do we'll just have to fix it!

**Pull request merged**
