### PR TITLE
Bug fix for images where all values are zero.

### PR DESCRIPTION
**Pull request by mtoeltsch**
Fix bug that results in error message "vector too long" when image has only pixels of value zero.

### CODE REVIEW

**Comment by perdrix52** [comment]
That would indeed appear to prevent the vector size overflow, though I might have preferred to handle the problem based on setting the maximum value (fMax) based on the possible maximum for the bitmap type being processed (255 for a 1 byte type, 65535 for a two byte type, etc.) rather than iterating the whole bitmap (CDeepStack::ComputeOriginalHistogram()) as currently which is slow.  That approach would avoid the need to check for infinite.

**Comment by mtoeltsch** [comment]
Ok, good idea. Let me try that and see, how it might influence the histogram view at the bottom of the window.

**Comment by perdrix52** [comment]
Looking deeper I don't think that quite works.   CStackedBitmap max value depends on two things - number of stacked bitmaps and the max per bitmap (which may be 65535.0).

**Comment by perdrix52** [comment]
Not as simple as I first thought!

**Comment by mtoeltsch** [comment]
As discussed in Slack: I'm afraid we need to scan the image for the max value, but the time to do this is almost negligible compared to the rest of the function.
So I pushed a new commit that does that, parallelized by OPENMP.

**Pull request merged**
